Release FUT-2.6

diff --git a/tools/pset b/tools/pset
--- a/tools/pset
+++ b/tools/pset
@@ -1,10 +1,6 @@
 #!/usr/bin/env bash
 
 OPENSYNC_ROOT=$(dirname "$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")")
-#echo "OPENSYNC_ROOT=$OPENSYNC_ROOT"
-
-export PATH=$OPENSYNC_ROOT/tools:$OPENSYNC_ROOT/lib_testbed/generic/tools:$PATH
-export PYTHONPATH=$OPENSYNC_ROOT:$OPENSYNC_ROOT/lib_testbed/generic/tools:$PYTHONPATH
 
 
 PROMPT='
@@ -63,12 +59,12 @@ prun()
         if [[ $# -eq 0 || "$1" == "-h" || "$1" == "--help" ]]; then
             list_testbeds && show_tools
 
-            echo "Most of the tools require a testbed to be selected via the 'pset' command. To select a testbed, run:"
-            echo "    $0 <testbed_name>"
+            echo "Most of the tools require a testbed to be selected via the 'osrt shell' command. To select a testbed, run:"
+            echo "    osrt shell <testbed_name>"
             echo "A testbed environment runs in a sub-shell. To leave it, use:"
             echo "    exit"
             echo "To run a single command on a testbed, use:"
-            echo "    $0 <testbed_name> <command> [<parameters>]"
+            echo "    osrt run <testbed_name> -- <command> [<parameters>]"
             echo; echo
 
             exit
@@ -82,87 +78,33 @@ prun()
             else
                 export debian_chroot="testbed:$OPENSYNC_TESTBED"
             fi
-            shift
-            cache-tb-config $1 || true
-            osrt reserve get . >&2
-            if [[ $# -eq 0 ]]; then
-                show_tools >&2
-            fi
-            if [[ $# -eq 0 ]]; then
-                set -- "${SHELL:-/bin/bash}"
-            fi
-            if [[ $@ == "/bin/bash" ]]; then
-                /bin/bash --rcfile "$FRAMEWORK_CACHE_DIR/bashrc"
+            if [[ $# -eq 1 ]]; then
+              cache-tb-config $1 || true
+              osrt testbed tools
+              osrt shell $OPENSYNC_TESTBED
             else
-                exec "$@"
+              shift
+              osrt run $OPENSYNC_TESTBED -- "$@"
             fi
         else
             echo "Configuration for location $1 not found."
             return 1
         fi
-
         return
     fi
 
-    if [[ -e "$OPENSYNC_ROOT/Pipfile.lock" ]]; then
-        if [[ $# -eq 0 || "$1" == "-h" || "$1" == "--help" ]]; then
-            list_testbeds && show_tools
-
-            echo "To activate the lib-testbed python environment, run:"
-            echo "    $0 pipenv"
-            echo "To deactivate the lib-testbed python environment, use:"
-            echo "   exit"
-            echo "Other examples:"
-            echo "    $0 pipenv ptopo --location-id ..."
-            echo "    $0 slotent pod pod3 ssh"
-            echo "    $0 slotent python test_cases/python/onboarding/node_health.py"
-            echo; echo
-
-            exit
-        fi
-
-        if [[ "$1" == "pipenv" ]]; then
-            echo "Activating pipenv..."
-            shift
-            cd $OPENSYNC_ROOT
-            if [[ $# -eq 0 ]]; then
-                export PROMPT_COMMAND=${PROMPT}
-                pipenv shell
-            else
-                pipenv shell "$@; exit"
-            fi
-            cd - > /dev/null
-        elif [[ "$1" == "exit" ]]; then
-            echo "Deactivating virtenv..."
-            unset OPENSYNC_TESTBED
-            exit
-        elif [[ -f $OPENSYNC_ROOT/config/locations/$1.yaml ]]; then
-            export OPENSYNC_TESTBED=$1
-            echo "Activating pipenv for $OPENSYNC_TESTBED"
-            shift
-            cd $OPENSYNC_ROOT
-            if [[ $# -eq 0 ]]; then
-                export PROMPT_COMMAND=${PROMPT}
-                pipenv shell "reserve . get && testbed tools"
-            else
-                pipenv shell "$@; exit"
-            fi
-            cd - > /dev/null
-        else
-            echo "Configuration for location $1 not found."
-            return 1
-        fi
-
-        return
+    if [[ -f $OPENSYNC_ROOT/config/locations/$1.yaml ]]; then
+        export OPENSYNC_TESTBED=$1
+        echo "Activating environment for $OPENSYNC_TESTBED"
+        cd $OPENSYNC_ROOT
+        . $OPENSYNC_ROOT/.venv/bin/pactivate
+        testbed tools
+        osrt shell $OPENSYNC_TESTBED
+        cd - > /dev/null
+    else
+        echo "Configuration for location $1 not found."
+        return 1
     fi
-
-    echo
-    echo "The environment (docker/pipenv) is not set up correctly."
-    echo "Use the supplied docker image for the correct environment."
-    echo
-    echo "For further details, see $OPENSYNC_ROOT/README.md"
-    echo
-    return 1
 }
 
 prun "$@"
